#!/usr/bin/python3
import sys


def tonum(s):   
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    try:
        ans += float(ine)
    except:
        ans += float(line)

print(ans)


